name: Shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  get: ^4.6.1
  url_launcher: ^6.0.20
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - packages/shrine_images/0-0.PNG
    - packages/shrine_images/1-0.PNG
    - packages/shrine_images/2-0.PNG
    - packages/shrine_images/3-0.PNG
    - packages/shrine_images/4-0.PNG
    - packages/shrine_images/5-0.PNG
    - packages/shrine_images/6-0.PNG
    - packages/shrine_images/7-0.PNG
    - packages/shrine_images/8-0.PNG
    - packages/shrine_images/9-0.PNG
    - packages/shrine_images/10-0.PNG
    - packages/shrine_images/11-0.PNG
    - packages/shrine_images/12-0.PNG
    - packages/shrine_images/13-0.PNG
    - packages/shrine_images/14-0.PNG
    - packages/shrine_images/15-0.PNG
    - packages/shrine_images/16-0.PNG
    - packages/shrine_images/17-0.PNG
    - packages/shrine_images/18-0.PNG